runtime: nodejs10

handlers:
  - url: /ngsw-worker.js
    static_files: build/static/ngsw-worker.js
    upload: build/static/ngsw-worker.js
  - url: /service-worker.js
    static_files: build/static/service-worker.js
    upload: build/static/service-worker.js
  - url: /ngsw.json
    static_files: build/static/ngsw.json
    upload: build/static/ngsw.json
  - url: /manifest.webmanifest
    static_files: build/static/manifest.webmanifest
    upload: build/static/manifest.webmanifest
    http_headers:
      Content-Type: application/manifest+json
  - url: /favicon.ico
    static_files: build/static/favicon.ico
    upload: build/static/favicon.ico
  - url: /apple-touch-icon.png
    static_files: build/static/apple-touch-icon.png
    upload: build/static/apple-touch-icon.png
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    redirect_http_response_code: 301
    secure: always
    http_headers:
      X-Frame-Options: SAMEORIGIN