x-google-marketplace:
  schemaVersion: v2
  applicationApiVersion: v1beta1
  publishedVersion: "0.2.18"
  publishedVersionMetadata:
    releaseNote: >-
      A first release.
  images:
    '':
      properties:
        import.image.repo:
          type: REPO_WITH_REGISTRY
        import.image.tag:
          type: TAG
    dicomweb-adapter-export:
      properties:
        export.image.repo:
          type: REPO_WITH_REGISTRY
        export.image.tag:
          type: TAG
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  
  lb.internal:
    type: boolean
    title: "Disable external access"
    description: >-
      Set to true for internal access in the same VPC network only. Choose false
      to expose the adapter to an external IP address.
    default: true
    enum:
    - true
    - false

  import.deployment_type:
      type: string
      title: "Deployment options"
      description: >-
        Choose adapter components to deploy.
        For details on importer:
        https://github.com/GoogleCloudPlatform/
        healthcare-dicom-dicomweb-adapter#import-adapter,
        for details on exporter:
        https://github.com/GoogleCloudPlatform/
        healthcare-dicom-dicomweb-adapter#export-adapter
      default: import adapter
      enum:
      - import adapter
      - export adapter
      - both
  import.dicomweb_address:
    type: string
    title: "Import Adapter: DICOMweb service address"
    description: >- 
      Address for DICOMweb service. Must be a full path up to /dicomWeb if 
      the Cloud Healthcare API is used. e.g. 
      https://healthcare.googleapis.com/v1/projects/myproject/locations/
      us-central1/datasets/mydataset/dicomStores/mydicomstore/dicomWeb
  import.dimse_aet:
    type: string
    title: "Import Adapter: DIMSE AET"
    description: DIMSE Application Entity Title.
    default: "IMPORTADAPTER"
  import.redact_remove_list:
    type: string
    title: "Import Adapter: Redact remove list (Optional)"
    description:  >-
      (Optional - Redactor) Tags to remove during C-STORE upload, comma 
      separated. Only one of 'redact' flags may be present.
  import.redact_keep_list:
    type: string
    title: "Import Adapter: Redact keep list (Optional)"
    description:  >-
      (Optional - Redactor) Tags to keep during C-STORE upload, comma separated.
      Only one of 'redact' flags may be present.
  import.dimse_cmove_aet:
    type: string
    title: "Import Adapter: C-MOVE AET (Optional)"
    description:  >-
      (Optional - C-MOVE) Separate Application Entity Tilte used for C-STORE calls within context of C-MOVE.
      For details, go to:
      https://github.com/GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#import-adapter
  import.aet_dictionary_inline:
    type: string
    title: "Import Adapter: Inline AET dictionary (Optional)"
    description:  >-
      (Optional - C-MOVE) Json array containing Application Entity definitions (name/host/port per element).
      e.g. [{"name":"DEVICE_A","host":"localhost","port":11113},
      {"name":"DEVICE_B","host":"192.168.0.1","port": 11114},...]
      For details, go to:
      https://github.com/GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#import-adapter
  import.destination_config_inline:
    type: string
    title: "Import Adapter: Destination config inline (Optional)"
    description:  >-
      (Optional) Json array containing destination definitions 
      (filter/dicomweb_destination per element).
  import.store_compress_to_transfer_syntax:
    type: string
    title: "Import Adapter: Store compress to transfer syntax (Optional)"
    description:  >-
      (Optional) Transfer Syntax to convert instances to during C-STORE 
      upload. See Readme for list of supported syntaxes.
  import.monitoring_project_id:
      type: string
      title: "Import Adapter: Monitoring project id (Optional)"
      description: >-
        (Optional) Stackdriver monitoring project id, must be the same as the 
        project id in which the adapter is running.
  import.custom_flags:
      type: string
      title: "Extra import adapter flags (Optional)"
      description: >-
        (Optional) Addtional flags for the import adapter.
        e.g. "--flag_a=valueA"

  export.peer_dimse_aet:
    type: string
    title: "Export Adapter: Peer DIMSE AET"
    description: (CStore) Application Entity Title of the DIMSE peer.
  export.peer_dimse_ip:
    type: string
    title: "Export Adapter: Peer DIMSE IP"
    description: (CStore) IP of DIMSE peer.
  export.peer_dimse_port:
    type: integer
    title: "Export Adapter: Peer DIMSE port"
    description: (CStore) Port of DIMSE peer.
  export.project_id:
    type: string
    title: "Export Adapter: Pubsub project id"
    description:  >-
      Pubsub project id, must be the same as the project id in which the adapter is running.
  export.subscription_id:
    type: string
    title: "Export Adapter: Pubsub subscription id"
    description: The pubsub subscription id
  export.dicomweb_addr:
    type: string
    title: "Export Adapter: DICOMweb address"
    description: >-
      Base api endpoint. e.g. 
      https://healthcare.googleapis.com/v1
  export.oauth_scopes:
    type: string
    title: "Export Adapter: Oauth scopes"
    description: Comma seperated OAuth scopes used by adapter.
    default: "https://www.googleapis.com/auth/pubsub"
  export.peer_dicomweb_address:
    type: string
    title: "Export Adapter: Peer DICOMweb address"
    description:  >-
      (StowRs) Address of peer DICOMweb API serving STOW-RS. Must be a full path up 
      to /dicomWeb if the Cloud Healthcare API is used. e.g. 
      https://healthcare.googleapis.com/v1/projects/myproject/locations/
      us-central1/datasets/mydataset/dicomStores/mydicomstore/dicomWeb
  export.use_gcp_application_default_credentials:
    type: boolean
    title: "Export Adapter: Enable gcp application default credentials"
    description:  >-
      (StowRs) If true, uses GCP Application Credentials to when sending HTTP requests 
      to peer. This is useful if the peer DICOMweb endpoint is running in GCP.
    enum:
    - true
    - false
  export.monitoring_project_id:
    type: string
    title: "Export Adapter: Monitoring project id (Optional)"
    description:  >-
      (Optional) Stackdriver monitoring project id, must be the same as the project 
      id in which the adapter is running.
  export.custom_flags:
      type: string
      title: "Extra export adapter flags (Optional)"
      description: >-
        (Optional) Addtional flags for the export adapter.
        e.g. "--flag_a=valueA"

required:
- name
- namespace
