version: 2.1
jobs:
  build:
    environment:
      GO111MODULE: "on"
    docker:
      - image: docker.mirror.hashicorp.services/circleci/golang:latest
    working_directory: /go/src/github.com/hashicorp/envconsul
    steps:
      - checkout
      - restore_cache:
          keys:
            - ct-modcache-v1-{{ checksum "go.mod" }}
      - run: |
          go test -v
      - save_cache:
          key: ct-modcache-v1-{{ checksum "go.mod" }}
          paths:
            - /go/pkg/mod
