name: "Trigger Test Boundary UI release"


on:
  workflow_dispatch:
    inputs:
      branch:
        description: Please use tag-like format n.n.n-someword (1.111.11-beta)
        required: true

jobs:
  trigger-circleci-release:
    runs-on: ubuntu-latest
    steps:

      - name: Trigger Release job
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Triggering Test release using BRANCH and TEST_TAG ${{ github.event.inputs.branch }}"

          curl -u ${{ secrets.CIRCLE_TOKEN }}: -X POST --header "Content-Type: application/json" \
          -d '{ "branch": "main", "parameters": {"TAG": "'${{ github.event.inputs.branch }}'" }}' \
          https://circleci.com/api/v2/project/github/hashicorp/boundary-ui-releases/pipeline
