name: "Trigger Boundary UI release"

on:
  push:
    tags:
      - '*'

jobs:
  trigger-circleci-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Trigger Release job
        run: |
          echo "Triggering release with a TAG ${GITHUB_REF#refs/tags/}"

          curl -u ${{ secrets.CIRCLE_TOKEN }}: -X POST --header "Content-Type: application/json" \
          -d '{ "branch": "main", "parameters": {"TAG": "'${GITHUB_REF#refs/tags/}'" }}' \
          https://circleci.com/api/v2/project/github/hashicorp/boundary-ui-releases/pipeline
