# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Deploy this DaemonSet to enable hyper-threading on the nodes with the
# "cloud.google.com/gke-smt-disabled=false" label.
#
# WARNING: Enabling hyper-threading may make the node vulnerable to 
# Microarchitectural Data Sampling (MDS). Please ensure that this is acceptable
# before deploying this to your production clusters.
#
# WARNING: Enabling hyper-threading requires node reboot. Therefore, in order
# to avoid disrupting your workloads, it is recommended to create a new node
# pool with the "cloud.google.com/gke-smt-disabled=false" label in your cluster,
# deploy the DaemonSet to enable hyper-threading in that node pool, and then
# migrate your workloads to the new node pool.

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: enable-smt
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: enable-smt
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: enable-smt
    spec:
      tolerations:
      - operator: Exists
      volumes:
      - name: host
        hostPath:
          path: /
      initContainers:
      - name: enable-smt
        image: bash
        command:
        - /usr/local/bin/bash
        - -c
        - |
          set -euo pipefail
          function check_not_secure_boot() {
            if [[ ! -d "/sys/firmware/efi" ]]; then
              return
            fi

            efi="$(mktemp -d)"
            mount -t efivarfs none "${efi}"

            # Read the secure boot variable.
            secure_boot="$(hexdump -v -e '/1 "%02X "' ${efi}/SecureBoot-*)"

            # Clean up
            umount "${efi}"
            rmdir "${efi}"

            # https://wiki.archlinux.org/index.php/Secure_Boot
            if [[ "${secure_boot}" == "06 00 00 00 01 " ]]; then
              echo "Secure Boot is enabled. Boot options cannot be changed."
              exit 1
            fi
          }
          function enable_smt_cos {
            local -r dir="$(mktemp -d)"
            mount /dev/sda12 "${dir}"
            sed -i -e "s| nosmt||g" "${dir}/efi/boot/grub.cfg"
            umount "${dir}"
            rmdir "${dir}"
          }
          function enable_smt_ubuntu {
            rm /host/etc/default/grub.d/99-nosmt.cfg
          }
          function enable_smt {
            if [[ ! $(grep " nosmt " /proc/cmdline) ]]; then
              echo "SMT has been enabled"
              return
            fi
            source /host/etc/os-release
            echo "Attempting to enable SMT for ${NAME}"
            check_not_secure_boot
            case "${NAME}" in
              "Container-Optimized OS") enable_smt_cos;;
              "Ubuntu") enable_smt_ubuntu;;
              *)
                echo "${NAME} is not supported"
                exit 1
                ;;
            esac
            echo "SMT enabled, rebooting for it to take effect"
            chroot /host systemctl reboot
          }
          enable_smt
        volumeMounts:
        - name: host
          mountPath: /host
        resources:
          requests:
            memory: 5Mi
            cpu: 5m
        securityContext:
          privileged: true
      containers:
      - image: gcr.io/google-containers/pause:2.0
        name: pause
      # Ensures that the pods will only run on the nodes having the certain
      # label.
      nodeSelector:
        "cloud.google.com/gke-smt-disabled": "false"
