archives:
  - files:
      - none*
    format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
before:
  hooks:
    - go mod download
builds:
  - binary: '{{ .ProjectName }}_{{ .Version }}'
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    ignore:
      - goarch: arm
        goos: windows
      - goarch: arm64
        goos: freebsd
      - goarch: arm64
        goos: windows
    ldflags:
      - -s -w -X main.Version={{.Version}}
    mod_timestamp: '{{ .CommitTimestamp }}'
changelog:
  skip: true
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
release:
  disable: true
