language: go
go:
  - 1.15.x

jobs:
  include:
    - name: Lint
      script: make lint
    - name: Test
      script: make test
    - name: Docs
      script: make deploy-docs
      if: branch = master AND NOT type = pull_request

notifications:
  email: false
