version: "2.1"

services:
    db:
        image: mysql:5.7
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database

    prometheus:
        image: prom/prometheus:v2.4.3
        command:
            - '--config.file=/etc/prometheus/prometheus.yaml'
            - '--storage.tsdb.path=/prometheus'
        volumes:
            - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
        depends_on:
            - dockerhost

    jaeger:
        image: jaegertracing/all-in-one:latest
        environment:
            COLLECTOR_ZIPKIN_HTTP_PORT: 9411

    dockerhost:
        image: qoomon/docker-host
        cap_add:
            - NET_ADMIN
            - NET_RAW
        restart: on-failure
