defaults: 
  before_script: 
    - cd /gcpviz
  image: 
    name: gcr.io/YOUR-PROJECT/gcpviz
  variables: 
    CAI_BUCKET_NAME: <YOUR-BUCKET>
    ORGANIZATION_ID: <YOUR-ORGANIZATION

stages: 
  - export_cai
  - generate_graphs

export_cai: 
  stage: export_cai
  script: 
    - /gcpviz/wait_for_export.sh gcloud asset export --output-path=gs://$CAI_BUCKET_NAME/resource_inventory.json --content-type=resource --organization=$ORGANIZATION_ID
    - gsutil cp://$CAI_BUCKET_NAME/resource_inventory.json .

generate_graphs: 
  stage: generate_graphs
  script:
    - /gcpviz/gcpviz.sh network --graph-title "Network connectivity" --query-file queries/network-basic.js
    - dot -Kdot -Tpng network.gv -o network.png
  


