dist: trusty
sudo: required
services:
  - docker
language: go
go:
  - "1.12.x"

script:
  - make test
  - make vet

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

env:
  - GOFLAGS=-mod=vendor GO111MODULE=on