trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - tests/*
    - readme.md

pr:
  autoCancel: true

# Build and Test
stages:
- stage: Build
  displayName: Build and Test
  jobs:
  - template: azure-pipelines-extension-build.yml
    parameters:
      publisher: $(publisher)
      tasks:
        - VaultInstaller
        - Vault

# Staging Extension release
- stage: Release
  jobs:
  - template: azure-pipelines-extension-release.yml