# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
   - name: 'gcr.io/cloud-builders/docker'
     args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/todo-api', '.' ]
     dir: "code/middleware"
   - name: 'gcr.io/cloud-builders/docker'
     args: ['push', 'gcr.io/$PROJECT_ID/todo-api']   
   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
     entrypoint: bash
     args: ['-c', 'gcloud run deploy todo-api --image gcr.io/$PROJECT_ID/todo-api --region $_REGION --allow-unauthenticated --vpc-connector vpc-connector --add-cloudsql-instances todo-db --set-env-vars todo_user=todo_user,todo_pass=todo_pass,todo_host=$$SQLHOST,todo_name=todo,REDISPORT=6379,REDISHOST=$$REDISHOST']
     secretEnv: ["REDISHOST","SQLHOST"]          
   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
     entrypoint: bash
     args: [ './massage.sh', '$_REGION' ]
     dir: "code/frontend"
   - name: 'gcr.io/cloud-builders/docker'
     args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/todo-fe', '.' ]
     dir: "code/frontend"
   - name: 'gcr.io/cloud-builders/docker'
     args: ['push', 'gcr.io/$PROJECT_ID/todo-fe']
   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
     entrypoint: gcloud
     args: [ 'run', 
              'deploy', 
              'todo-fe', 
              '--image', 'gcr.io/$PROJECT_ID/todo-fe', 
              '--region', '$_REGION', 
              '--allow-unauthenticated', 
              '--port', '80']    
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/sqlhost/versions/latest
    env: 'SQLHOST'
  - versionName: projects/$PROJECT_ID/secrets/redishost/versions/latest
    env: 'REDISHOST'              
substitutions:
  _REGION: us-central1