# Copyright 2015 Google Inc. All Rights Reserved.

# Phony app.yaml file for devappserver.

module: default
runtime: python27
vm: true
api_version: 1
threadsafe: true

resources:
    cpu: .5
    memory_gb: 1.3

manual_scaling:
    instances: 1

handlers:
- url: /.*
  script: phony.app
