# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
# Build Container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/magic-github-proxy:$BUILD_ID', '.']

# Push to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/magic-github-proxy:$BUILD_ID"]

# Prepare Kubernetes Manifest
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-e'
  - '-c'
  - |

    # Dynamically create service name based on the current project ID
    SERVICE_NAME=magic-github-proxy.endpoints.$PROJECT_ID.cloud.goog

    # Obtain the service config ID created by the deployment to Cloud Endpoints
    SERVICE_CONFIG_ID=`gcloud endpoints services describe $$SERVICE_NAME --format=value\(serviceConfig.id\)`

    # Substitute variables && create new Kubernetes Manifest
    mkdir -p target
    cat kubernetes/deployment.yaml | \
      sed s/BUILD_ID/$BUILD_ID/g | \
      sed s/PROJECT_ID/$PROJECT_ID/g | \
      sed s/SERVICE_NAME/$$SERVICE_NAME/g | \
      sed s/KMS_LOCATION/$_KMS_LOCATION/g | \
      sed s/KMS_KEY_RING/$_KMS_KEY_RING/g | \
      sed s/KMS_KEY/$_KMS_KEY/g | \
      sed s/BUCKET_NAME/$_BUCKET_NAME/g | \
      sed s/PRIVATE_FILE/$_PRIVATE_FILE/g | \
      sed s/CERTIFICATE_FILE/$_CERTIFICATE_FILE/g \
      > target/deployment.yaml

# Perform Kubernetes Deployment
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-e'
  - '-c'
  - |
    gcloud container clusters get-credentials --project="$PROJECT_ID" --zone="$_ZONE" "$_CLUSTER"

    kubectl apply -f target/deployment.yaml
images:
- 'gcr.io/$PROJECT_ID/magic-github-proxy'
