dist: trusty
sudo: required
services:
- docker
language: go
go:
- 1.11.x
env: GO111MODULE="on"
before_install:
- openssl aes-256-cbc -K $encrypted_63eeb4149724_key -iv $encrypted_63eeb4149724_iv
  -in scripts/getgocookie.sh.enc -out scripts/getgocookie.sh -d
- bash scripts/getgocookie.sh
script:
- make test
- make vet
branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
