language: java

jdk:
  - oraclejdk8
  - openjdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# https://github.com/travis-ci/travis-ci/issues/5227
sudo: false
