crash_courses:
  - title: Terraform
    duration: 2 hours
    price: $400 / person
    description: |
      Get up and running quickly with Terraform by learning the syntax of HCL, how to manage state, how to package infrastructure into reusable Terraform modules, how to fit Terraform into your CI/CD workflow, and best practices for using Terraform as a team.

  - title: Packer, Docker, and ECS
    duration: 2 hours
    price: $400 / person
    description: |
      Learn how to package your code into immutable images that run exactly the same way everywhere using Packer and Docker, as well as how to run Docker images in AWS with the EC2 Container Service (ECS).

  - title: AWS fundamentals
    duration: 2 hours
    price: $400 / person
    description: |
      This course walks you through all the basics of AWS, including how to use EC2, IAM, Auto Scaling Groups, Elastic Load Balancing, EC2 Container Service, RDS, S3, SQS, Lambda, and more.

  - title: DevOps fundamentals
    duration: 2 hours
    price: $400 / person
    description: |
      A practical guide to setting up a software delivery process to take your code from dev to prod in a way that is automated, reliable, and secure. The course covers continuous integration, continuous delivery, automated tests, automated deployment, dependencies, microservices, infrastructure as code, feature toggles, monitoring, alerting, log aggregation, high availability, scalability, and more.

  - title: Security fundamentals
    duration: 2 hours
    price: $400 / person
    description: |
      Learn security best practices, including how to manage passwords for yourself and your team, expose secrets to your applications, manage user accounts and permissions in AWS with IAM, define a secure network topology in your VPCs, control access to servers with SSH and VPN, harden servers with permission settings and intrusion detection, and more.

  - title: AWS Lambda
    duration: 1 hour
    price: $400 / person
    description: |
      Learn how to build serverless applications using AWS Lambda, including how to develop and test Lambda functions locally, how to deploy Lambda functions across multiple environments using Terraform, and how to trigger Lambda functions using a variety of events (SQS, Kinesis, API Gateway, etc).

workshops:
  - title: Infrastructure as Code with Terraform
    duration: 2 days
    price: $2,000 / person
    description: |
      Get up &amp; running quickly with Terraform using real-world examples. You’ll deploy servers, databases, and load balancers on AWS; you’ll build immutable infrastructure with Docker and Packer; and you’ll put it all together into a continuous delivery pipeline. This workshop covers Terraform’s syntax, the CLI, state management, modules, team workflows, environment management, versioning, gotchas, and more.

  - title: The modern end-to-end tech stack
    duration: 2 days
    price: $2,000 / person
    description: |
      A whirlwind tour of all the pieces you need to create a modern tech stack. Learn about server clusters and Docker clusters; server-side frameworks and client-side frameworks; relational databases, NoSQL databases, schema management, and stream processing; monitoring, alerting, and log aggregation; network security, secret storage, TLS, SSH, and VPN; continuous integration, continuous delivery, automated deployment, feature toggles, and dark launches; static content, CDNs, and versioning; scalability, high availability, and performance; and more.
