dist: xenial
sudo: required
services:
- docker
language: go
go:
- 1.13.x

install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh

script:
- make test
- make vet
- make website-test
- travis_wait 50 make testacc

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
env:
  global:
    - GOFLAGS=-mod=vendor
    # GRIDSCALE_URL, GRIDSCALE_UUID, GRIDSCALE_TOKEN variables for testacc target
    - secure: QpBW8RHF02LpMEkkEbtFje2tq64mNfm6mfHEVNkB9NSZ5QUEHTF7jaFAghgfQxuTOZ2JKHjXy22cs4Rch1LE06B2qIax3dIzSm8dib8g8ArcQVOl+ZBUt0IiuHzwMdGkvIcQH0VrlHULKbzg5BSoFytSmYvk5Xs14au8UEkVmFsHuZD9rzHcbHwAyn8Ebjkx8cw00QdmPJl8MopdEEmf3RMdIlmzTfFhbGdPHpwp/QPkCz90bWsyrtVorUCNYpEI91UDoaH5AtMiIWKDvVe0vZLAvRjvafa6Awa3GiQl60QUvBhIVnS1FeQ0wFykS7rmIFwhkhZ9yoBbvzd8rx5Q5coikXbmZPgnKlWlHW6GnCgrNLKPdKwe4o4ZFMrW8wgM6xCnwK5Fx677ELHnIX02Vb7h0SFwrvhVKmLGiKnSfY9XH0OvQ7xLjOd5+caq/r5/Pe7ukqbNSQH4RlyJxSvAhxPa8xkgblY7IUxrqJe+kQjdLa54th14YGB2sWluLKlCYHtRaz+0N5NHMCR9qvkWlswXPv0BAb5Uol7LoSyTmjWLyhaGBW69B9ZD4S9+eQKYayNII6+ZOymWi+QyFvEsXt9JvoChZFV8C9taTzjQOuwtz/p/HKG5FNjm5qGAfWcepvQYhGLSVTISW85fLmrliRf12sGS8Zu2Yc2wQrqvvzw=
    - secure: HZqHKB3jmvDOsGPIKDb7TYIaoo2bpgdtFZSMfSoYaTHLPaU4eSOuXS9Rek87W6CpvLNkwjD3CZq+QBWphj2i1+FDO1+SdPnbYeq8xANnalTKyPcmZP/G83d/dfaJ7pbR8kfz+pELspRjrgf55AVBRDw3oLcXYIpsvsmhnp6LVM+BSqxlGVmEn9nVI2B2It9VLj+NdUjZAFcP3aenb+B+FU/1/FEC6OdcvtGwKVZbT18vAZ4qz5R2G4XzqN5h9yEIQ/1XYcYul6VdMgM321BC3ZDwJLv8X3ypr8NR1VqpGk7jiBp8SHzGMUH2aX381zH1BCby2bm9kaMLKV9A2bgtVA0Mnw2btalAo7M6FxT4hr7ZwAWLtje+kC1V+KThu5h4pMEZC7vtkLdkajv/QGi/PWuq7jPajAQR3VpGOgVxtZmgAZUMvU3r3rKTurHbG6M7nZxYUlq41rtty70v+S7oO2us8psSY9xAPWIWsVZRD0os3JXdzvrJPO/NaOKwFmUERNfzkLsF2seZF64D5UHuGhMnAS9NzNtTq3wnkhYxxodEDdWSS3zLctCgNDMSx7webozg3FGhajpxT/bYTyUjIj3etee7l36JMKsinJyXFYllyPSJXJVT6jw2JmonMZIFuynFPBbmXOF/5ZQ3oWsmyKc36MlMHncvUAQoif7qTpQ=
    - secure: Z7su/hnjmw878lOMzRYBO4+F598nfADIZNRwTSNBRUzWu0M0y8p9pZZZdEDxT95q3nAxnkhMgFlFlnAZg0JkGC2oVDGYPzBucnbQjVUp3MUWToNkJQNX+J6Bh6f+SSZrtns1EuI+63uuTQ+1+SulMxGRnwJJz+EhsAHWYLxXiyWdwf71DWeO4Z7BX1gxSfGOdjRC9AgRjVOUdO2kqO6hTZSsoTHiH8VkUazxFid1ABUxLHdyfntrv+qi8FZejTFz2K8mzWi6mBnJDx1RV8asm6bdozfswQnixDSKOdkIf8EB7OsdiHg/MwSQlFWpw3xuWDQHWDUQnZ05pAo9dag0pVYqWnWwFN77rof/JT8ZzNTOcaBh5HTzvwusrDrh3FCjQBidAElR2oyKX5t2segGKv2Xe24ppfVCXTpHkmRNTx1HQGvFDMPyn9GxFL+biqiwWlqt3rQvxHIDHcaty9I39yC2c+z4UcHWbacScxZUCsD0QIPt1WtLBeKHGU5jRjq3O4IeMw4j9fnJjN9xtGtuGOp1r9PoKphBBc2ITcUCnN8264zN3e7ht0VS6+TCxcjN0aW6bbgyoHAl52cGNLA+JM6IQ2BXJcIjRh83gNxFqqcJy1Jgj9Zo9T5gDc9FOYl+uB4vJsOXCeeJ87K5E1DH83ZStskatVsNOJQkGds4j5U=
