common: &common
  loglevel: info
  storage: gcs
  oauth2: true
  boto_bucket: "_env:GCS_BUCKET"
  secret_key: "_env:SECRET_KEY"
  storage_path: "_env:STORAGE_PATH:/"
  standalone: true

dev:
  <<: *common
  loglevel: debug

prod:
  <<: *common
  loglevel: warn
