name: build

on:
  push:
  pull_request:

jobs:
  run-tests:
    name: Run test cases
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go: [^1]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Make sure we build on all platforms
        run: |
          go build
